name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install awsebcli

      - name: Run tests
        run: pytest -v

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: Initialize EB CLI
        run: |
          eb init ${{ secrets.EB_APPLICATION_NAME }} \
            --platform python-3.11 \
            --region ${{ secrets.AWS_REGION }} \
            --quiet

      - name: Deploy to Elastic Beanstalk
        run: |
          eb deploy ${{ secrets.EB_ENVIRONMENT_NAME }} --timeout 15
