name: Health Check

on:
  schedule:
    - cron: '*/5 * * * *'  # Co 5 minut
  workflow_dispatch:

jobs:
  health-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check health status
      run: |
        # Pobierz adres URL z sekretów
        APP_URL=${{ secrets.APP_HEALTH_CHECK_URL }}
        
        # Wykonaj żądanie health check
        response=$(curl -s -o /dev/null -w "%{http_code}" "$APP_URL/health")
        
        if [ "$response" -ne 200 ]; then
          echo "Health check failed! Status code: $response"
          exit 1
        else
          echo "Health check passed!"
        fi